### ISSUE TITLE
`bool` is not in the list of allowed variables - cifar

### ISSUE THREAD

**Issue by HamedMP** [uber/horovod#77] opened 2017-11-06 16:46 UTC
I'm running `Cifar10` implementation adopted for Horovod on gpu cluster (with 4 and another time 8 gpus) and I get the following error. 
The code is working on the local machine when horovod codes removed, no problem with the tensorflow implementation I guess. Also on the cluster, the `mnist` example runs perfectly so the setup also looks okay. 

My guess is that it's something with `horovod_broadcast`.

```bash
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[27685,1],0]
  Exit code:    1
--------------------------------------------------------------------------


 STDERR: INFO:tensorflow:Create CheckpointSaverHook.
Traceback (most recent call last):
  File "/data/hadoop-2.8.2.1/tmp/nm-local-dir/usercache/WLxuXLFw1KZBatf4JlKiQVx2fB-Nwe4CDQUcvyKfLbY/appcache/application_1508601191819_0234/container_e22_1508601191819_0234_01_000003/cifar_horovod-2.py", line 191, in <module>
    with tf.train.SingularMonitoredSession(hooks=hooks, config=config) as sess:
  File "/srv/hops-gpu/anaconda/anaconda/envs/robin_allreduce/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 750, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/srv/hops-gpu/anaconda/anaconda/envs/robin_allreduce/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 483, in __init__
    h.begin()
  File "/srv/hops-gpu/anaconda/anaconda/envs/robin_allreduce/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 115, in begin
    self.bcast_op = broadcast_global_variables(self.root_rank)
  File "/srv/hops-gpu/anaconda/anaconda/envs/robin_allreduce/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 90, in broadcast_global_variables
    for var in tf.global_variables()])
  File "/srv/hops-gpu/anaconda/anaconda/envs/robin_allreduce/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 187, in broadcast
    return MPI_LIB.horovod_broadcast(tensor, name=name, root_rank=root_rank)
  File "<string>", line 90, in horovod_broadcast
  File "/srv/hops-gpu/anaconda/anaconda/envs/robin_allreduce/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 589, in apply_op
    param_name=input_name)
  File "/srv/hops-gpu/anaconda/anaconda/envs/robin_allreduce/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'tensor' has DataType bool not in list of allowed values: uint8, int8, uint16, int16, int32, int64, float32, float64


	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
17/11/06 17:38:16 INFO CoarseGrainedExecutorBackend: Got assigned task 11
17/11/06 17:38:16 INFO Executor: Running task 0.3 in stage 0.0 (TID 11)
17/11/06 17:38:16 INFO Executor: Executor is trying to kill task 0.3 in stage 0.0 (TID 11), reason: stage cancelled
```

**Comment by alsrgv** [comment] 2017-11-06 18:35
@HamedMP, thanks for reporting this!  We will push out a version with `bool` support shortly.

**Comment by HamedMP** [comment] 2017-11-06 20:16
Thanks @alsrgv for the fast reply, looking forward to it!

**Comment by alsrgv** [comment] 2017-11-07 01:55
@HamedMP, Horovod 0.10.1 with boolean `broadcast()` and `allgather()` has been released. Can you try it out and confirm that your Cifar10 training script works?

**Comment by HamedMP** [comment] 2017-11-07 11:14
Hey @alsrgv , The bool operator works (as far as I don't get that error anymore)

But there is another issue which I think I might open another issue (as you suggest and if it can be related to horovod)

I get `You must feed a value for placeholder tensor 'input/image' with dtype float and shape [?,32,32,3]` but the same code without using horovod runs smoothly on the same machine with 1 GPU. 
(I use a feed_dict that calls an input_fn which is tf.Dataset object initialized by make_one_shot_iterable and calling iterator.get_next())

Adding horovod init, opt(), and hooks, as described in the mnist example, throws the error above. 

My guess is that the tf.Dataset operations is not fully supported or there are some incompatibilities there. 

[Another issue which is related to **Data input pipeline** using horovod was when using `tf.learn dataset` or `keras.datasets` to handle the situation, each process (in my case 8 processes from 8 gpus) started to download the data so I had to change it to use Dataset APIs]

**Comment by alsrgv** [comment] 2017-11-07 18:22
@HamedMP, can you publish a full code for this example somewhere, so I could try to repro it in my lab?

**Comment by HamedMP** [comment] 2017-11-07 18:47
Yeah, sure, 

The cifar data is converted to `.tfrecords` using [this code](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10_estimator/generate_cifar10_tfrecords.py)

```python
import tensorflow as tf
import horovod.tensorflow as hvd

from tflearn.data_utils import shuffle, to_categorical
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.estimator import regression
from tflearn.data_preprocessing import ImagePreprocessing
from tflearn.data_augmentation import ImageAugmentation


tf.logging.set_verbosity(tf.logging.DEBUG)
num_input = 32*32*3
batch_size = 128
num_classes = 10

# Adjust number of epochs based on number of GPUs.
epochs = 256

last_step = 100000
evaluation_step = 100

logdir = "path/to/logdir"
data_dir = "cifar10/data/"
train_filenames = [data_dir + "train.tfrecords"]
validation_filenames = [data_dir + "validation.tfrecords"]
test_filenames = [data_dir + "eval.tfrecords"]


def data_input_fn(filenames, batch_size=batch_size, shuffle=False, repeat=None):

    def parser(serialized_example):
        """Parses a single tf.Example into image and label tensors."""
        features = tf.parse_single_example(
            serialized_example,
            features={
                'image': tf.FixedLenFeature([], tf.string),
                'label': tf.FixedLenFeature([], tf.int64),
            })
        image = tf.decode_raw(features['image'], tf.uint8)
        image.set_shape([num_input])

        image = tf.cast(
            tf.transpose(tf.reshape(image, [3, 32, 32]), [1, 2, 0]),
            tf.float32)

        # Normalize the values of the image from the range [0, 255] to [-0.5, 0.5]
        image = tf.cast(image, tf.float32) / 255 - 0.5
        label = tf.cast(features['label'], tf.int32)
        label = tf.one_hot(label, num_classes)
        return image, label

    def _input_fn():
        dataset = tf.contrib.data.TFRecordDataset(filenames)

        # Map the parser over dataset, and batch results by up to batch_size
        dataset = dataset.map(parser, num_threads=1, output_buffer_size=batch_size)
        if shuffle:
            dataset = dataset.shuffle(buffer_size=10000)
        dataset = dataset.batch(batch_size)
        dataset = dataset.repeat(repeat)
        iterator = dataset.make_one_shot_iterator()

        features, labels = iterator.get_next()

        return features, labels

    return _input_fn

# Convolutional network building
def model(features):
    tf.summary.image("image", features)
    network = conv_2d(features, 32, 3, activation='relu')
    network = max_pool_2d(network, 2)
    network = conv_2d(network, 64, 3, activation='relu')
    network = conv_2d(network, 64, 3, activation='relu')
    network = max_pool_2d(network, 2)
    network = fully_connected(network, 512, activation='relu')
    network = dropout(network, 0.5)
    logits  = fully_connected(network, 10, activation='linear')

    return logits

# Build model...
with tf.name_scope('input'):
    # Placeholders for data and labels
    X = tf.placeholder(shape=(None, 32, 32, 3), dtype=tf.float32, name='image')
    Y = tf.placeholder(shape=(None, 10), dtype=tf.float32, name='label')

preds = model(X)
# Defining other ops using Tensorflow
with tf.name_scope('Loss'):
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=preds, labels=Y))
    tf.summary.scalar('loss', loss)

opt = tf.train.RMSPropOptimizer(0.01)

# Initialize Horovod.
hvd.init()

# Add Horovod Distributed Optimizer.
opt = hvd.DistributedOptimizer(opt)

global_step = tf.contrib.framework.get_or_create_global_step()
train_op = opt.minimize(loss, global_step=global_step)

with tf.name_scope('Accuracy'):
    accuracy = tf.reduce_mean(
        tf.cast(tf.equal(tf.argmax(preds, 1), tf.argmax(Y, 1)), tf.float32),
        name='acc')
    # create a summary for our accuracy
    tf.summary.scalar("accuracy", accuracy)

# Initializing the variables
init = tf.global_variables_initializer()


# Get train and test iterators
train_input_fn = data_input_fn(train_filenames, batch_size=batch_size)
test_input_fn =  data_input_fn(test_filenames)

# BroadcastGlobalVariablesHook broadcasts variables from rank 0 to all other
# processes during initialization.
if hvd.local_rank()==0:
    hooks = [hvd.BroadcastGlobalVariablesHook(0),
         tf.train.StopAtStepHook(last_step=last_step),
         tf.train.LoggingTensorHook(tensors={'step': global_step, 'loss': loss},
                                    every_n_iter=10),
         tf.train.SummarySaverHook(save_steps=10,
                                   output_dir=logdir,
                                   summary_op=tf.summary.merge_all()),
        tf.train.CheckpointSaverHook(checkpoint_dir=logdir, save_steps=50)
         ]
else:
    hooks = [hvd.BroadcastGlobalVariablesHook(0),
             tf.train.StopAtStepHook(last_step=last_step)
             ]

# Pin GPU to be used to process local rank (one GPU per process)
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())
    
# The MonitoredTrainingSession takes care of session initialization,
# restoring from a checkpoint, saving to a checkpoint, and closing when done
# or an error occurs.
with tf.train.SingularMonitoredSession(hooks=hooks, config=config) as sess:
    print('Initialziing')
    sess.run(init)
    step = 0

    while step < last_step:
        # Run a training step synchronously.
        images_, labels_ = sess.run(train_input_fn())
        print(labels_)
        _, loss_, step = sess.run([train_op, loss, global_step], 
            feed_dict={X: images_, Y: labels_})
        print('Step: {}, Loss:{}'.format(str(step), str(loss_)))
        if step % evaluation_step == 0:
            images_test, labels_test = sess.run(test_input_fn())
            acc_, loss_ = sess.run([accuracy, loss], 
                feed_dict={X: images_test, Y: labels_test})
            print("Step:", '%03d' % step,
                  "Loss:", str(loss_),
                  "Accuracy:", str(acc_))

if __name__ == "__main__":
    print("STARTING")
    tf.app.run()
```

**Comment by alsrgv** [comment] 2017-11-07 19:22
@HamedMP,

I removed all the Horovod components, but I'm still getting this error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input/image' with dtype float and shape [?,32,32,3]
         [[Node: input/image = Placeholder[dtype=DT_FLOAT, shape=[?,32,32,3], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: Loss/Mean/_137 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_214_Loss/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

Can you share the code that is working for you without Horovod?

**Comment by HamedMP** [comment] 2017-11-07 21:18
Thank you @alsrgv for checking the code, yeah definitely, I just re-run the code below and it works fine, the only difference as far as I see is in the `SingularMonitoredSession` which is replaced by normal `tf.Session()` for using on single machine/gpu/cpu. 

```python

import tensorflow as tf

from tflearn.data_utils import shuffle, to_categorical
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.estimator import regression
from tflearn.data_preprocessing import ImagePreprocessing
from tflearn.data_augmentation import ImageAugmentation


tf.logging.set_verbosity(tf.logging.DEBUG)
num_input = 32*32*3
batch_size = 128
num_classes = 10

# Adjust number of epochs based on number of GPUs.
epochs = 256

last_step = 100000
evaluation_step = 100

lr = 0.01

logdir = "logs/"
data_dir = "data/"
train_filenames = [data_dir + "train.tfrecords"]
validation_filenames = [data_dir + "validation.tfrecords"]
test_filenames = [data_dir + "eval.tfrecords"]


def data_input_fn(filenames, batch_size=1000, shuffle=False, repeat=None):

    def parser(serialized_example):
        """Parses a single tf.Example into image and label tensors."""
        features = tf.parse_single_example(
            serialized_example,
            features={
                'image': tf.FixedLenFeature([], tf.string),
                'label': tf.FixedLenFeature([], tf.int64),
            })
        image = tf.decode_raw(features['image'], tf.uint8)
        image.set_shape([num_input])

        image = tf.cast(
            tf.transpose(tf.reshape(image, [3, 32, 32]), [1, 2, 0]),
            tf.float32)

        # Normalize the values of the image from the range [0, 255] to [-0.5, 0.5]
        image = tf.cast(image, tf.float32) / 255 - 0.5
        label = tf.cast(features['label'], tf.int32)
        label = tf.one_hot(label, num_classes)
        return image, label

    def _input_fn():
        dataset = tf.contrib.data.TFRecordDataset(filenames)

        # Map the parser over dataset, and batch results by up to batch_size
        dataset = dataset.map(parser, num_threads=1, output_buffer_size=batch_size)
        if shuffle:
            dataset = dataset.shuffle(buffer_size=10000)
        dataset = dataset.batch(batch_size)
        dataset = dataset.repeat(repeat)
        iterator = dataset.make_one_shot_iterator()

        features, labels = iterator.get_next()

        return features, labels

    return _input_fn


# Convolutional network building
def model(features):
    net = tf.reshape(features, [-1, 32, 32, 3])
    tf.summary.image("image", net)
    network = conv_2d(net, 32, 3, activation='relu')
    network = max_pool_2d(network, 2)
    network = conv_2d(network, 64, 3, activation='relu')
    network = conv_2d(network, 64, 3, activation='relu')
    network = max_pool_2d(network, 2)
    network = fully_connected(network, 512, activation='relu')
    network = dropout(network, 0.5)
    logits  = fully_connected(network, 10, activation='linear')

    return logits



# Build model...
with tf.name_scope('input'):
    # Placeholders for data and labels
    X = tf.placeholder(shape=(None, 32, 32, 3), dtype=tf.float32, name='image')
    Y = tf.placeholder(shape=(None, 10), dtype=tf.float32, name='label')

preds = model(X)
# Defining other ops using Tensorflow
with tf.name_scope('Loss'):
#         loss = tf.losses.sparse_softmax_cross_entropy(Y, logits)
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=preds, labels=Y))
    tf.summary.scalar('loss', loss)

opt = tf.train.RMSPropOptimizer(lr)

global_step = tf.contrib.framework.get_or_create_global_step()
train_op = opt.minimize(loss, global_step=global_step)

with tf.name_scope('Accuracy'):
    accuracy = tf.reduce_mean(
        tf.cast(tf.equal(tf.argmax(preds, 1), tf.argmax(Y, 1)), tf.float32),
        name='acc')
    # create a summary for our accuracy
    tf.summary.scalar("accuracy", accuracy)

# Initializing the variables
init = tf.global_variables_initializer()


# Get train and test iterators
train_input_fn = data_input_fn(train_filenames, batch_size=batch_size)
test_input_fn =  data_input_fn(test_filenames)

# The MonitoredTrainingSession takes care of session initialization,
# restoring from a checkpoint, saving to a checkpoint, and closing when done
# or an error occurs.
# with tf.train.MonitoredTrainingSession(hooks=hooks) as sess:
with tf.Session() as sess:
    print('Initialziing')
    sess.run(init)
    # sess.run(tf.summary.merge_all())
    step = 0

    while step < last_step:
        # Run a training step synchronously.

        images_, labels_ = sess.run(train_input_fn())
        # print(labels_)
        _, loss_, step = sess.run([train_op, loss, global_step], 
            feed_dict={X: images_, Y: labels_})
        print('Step: {}, Loss:{}'.format(str(step), str(loss_)))
        if step % evaluation_step == 0:
            images_test, labels_test = sess.run(test_input_fn())
            acc_, loss_ = sess.run([accuracy, loss], 
                feed_dict={X: images_test, Y: labels_test})
            print("Step:", '%03d' % step,
                  "Loss:", str(loss_),
                  "Accuracy:", str(acc_))

if __name__ == "__main__":
    print("STARTING")
    tf.app.run()

```

**Comment by alsrgv** [comment] 2017-11-07 21:47
I think the problem is that tf.data API doens't like SingularTrainingSession for some reason. Worth opening a ticket on TensorFlow GitHub.

We have an example with plain `tf.Session` [here](https://github.com/uber/horovod/blob/master/examples/tensorflow_word2vec.py), and I also modified your code:

```python
import tensorflow as tf

from tflearn.data_utils import shuffle, to_categorical
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.estimator import regression
from tflearn.data_preprocessing import ImagePreprocessing
from tflearn.data_augmentation import ImageAugmentation
import horovod.tensorflow as hvd


# Initialize Horovod
hvd.init()

tf.logging.set_verbosity(tf.logging.DEBUG)
num_input = 32*32*3
batch_size = 128
num_classes = 10

# Adjust number of epochs based on number of GPUs.
epochs = 256

last_step = 100000
evaluation_step = 100

lr = 0.01

logdir = "logs/"
data_dir = "data/"
train_filenames = [data_dir + "train.tfrecords"]
validation_filenames = [data_dir + "validation.tfrecords"]
test_filenames = [data_dir + "eval.tfrecords"]


def data_input_fn(filenames, batch_size=1000, shuffle=False, repeat=None):

    def parser(serialized_example):
        """Parses a single tf.Example into image and label tensors."""
        features = tf.parse_single_example(
            serialized_example,
            features={
                'image': tf.FixedLenFeature([], tf.string),
                'label': tf.FixedLenFeature([], tf.int64),
            })
        image = tf.decode_raw(features['image'], tf.uint8)
        image.set_shape([num_input])

        image = tf.cast(
            tf.transpose(tf.reshape(image, [3, 32, 32]), [1, 2, 0]),
            tf.float32)

        # Normalize the values of the image from the range [0, 255] to [-0.5, 0.5]
        image = tf.cast(image, tf.float32) / 255 - 0.5
        label = tf.cast(features['label'], tf.int32)
        label = tf.one_hot(label, num_classes)
        return image, label

    def _input_fn():
        dataset = tf.contrib.data.TFRecordDataset(filenames)

        # Map the parser over dataset, and batch results by up to batch_size
        dataset = dataset.map(parser, num_threads=1, output_buffer_size=batch_size)
        if shuffle:
            dataset = dataset.shuffle(buffer_size=10000)
        dataset = dataset.batch(batch_size)
        dataset = dataset.repeat(repeat)
        iterator = dataset.make_one_shot_iterator()

        features, labels = iterator.get_next()

        return features, labels

    return _input_fn


# Convolutional network building
def model(features):
    net = tf.reshape(features, [-1, 32, 32, 3])
    tf.summary.image("image", net)
    network = conv_2d(net, 32, 3, activation='relu')
    network = max_pool_2d(network, 2)
    network = conv_2d(network, 64, 3, activation='relu')
    network = conv_2d(network, 64, 3, activation='relu')
    network = max_pool_2d(network, 2)
    network = fully_connected(network, 512, activation='relu')
    network = dropout(network, 0.5)
    logits  = fully_connected(network, 10, activation='linear')

    return logits


# Build model...
with tf.name_scope('input'):
    # Placeholders for data and labels
    X = tf.placeholder(shape=(None, 32, 32, 3), dtype=tf.float32, name='image')
    Y = tf.placeholder(shape=(None, 10), dtype=tf.float32, name='label')

preds = model(X)
# Defining other ops using Tensorflow
with tf.name_scope('Loss'):
#         loss = tf.losses.sparse_softmax_cross_entropy(Y, logits)
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=preds, labels=Y))
    tf.summary.scalar('loss', loss)

opt = tf.train.RMSPropOptimizer(lr)

# Wrap with Distributed Optimizer
opt = hvd.DistributedOptimizer(opt)

global_step = tf.contrib.framework.get_or_create_global_step()
train_op = opt.minimize(loss, global_step=global_step)

with tf.name_scope('Accuracy'):
    accuracy = tf.reduce_mean(
        tf.cast(tf.equal(tf.argmax(preds, 1), tf.argmax(Y, 1)), tf.float32),
        name='acc')
    # create a summary for our accuracy
    tf.summary.scalar("accuracy", accuracy)

# Initializing the variables
init = tf.global_variables_initializer()

# Broadcast initial variable states from rank 0 to all other processes.
# This is necessary to ensure consistent initialization of all workers when
# training is started with random weights or restored from a checkpoint.
bcast = hvd.broadcast_global_variables(0)

# Get train and test iterators
train_input_fn = data_input_fn(train_filenames, batch_size=batch_size)
test_input_fn =  data_input_fn(test_filenames)

# Pin GPU to be used to process local rank (one GPU per process)
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())

# The MonitoredTrainingSession takes care of session initialization,
# restoring from a checkpoint, saving to a checkpoint, and closing when done
# or an error occurs.
# with tf.train.MonitoredTrainingSession(hooks=hooks) as sess:
with tf.Session(config=config) as sess:
    print('Initialziing')
    sess.run(init)
    sess.run(bcast)
    # sess.run(tf.summary.merge_all())
    step = 0

    while step < last_step:
        # Run a training step synchronously.

        images_, labels_ = sess.run(train_input_fn())
        # print(labels_)
        _, loss_, step = sess.run([train_op, loss, global_step],
            feed_dict={X: images_, Y: labels_})
        print('Step: {}, Loss:{}'.format(str(step), str(loss_)))
        if step % evaluation_step == 0:
            images_test, labels_test = sess.run(test_input_fn())
            acc_, loss_ = sess.run([accuracy, loss],
                feed_dict={X: images_test, Y: labels_test})
            print("Step:", '%03d' % step,
                  "Loss:", str(loss_),
                  "Accuracy:", str(acc_))

if __name__ == "__main__":
    print("STARTING")
    tf.app.run()
```

**Comment by HamedMP** [comment] 2017-11-07 21:53
Thank you @alsrgv I will just check it.
What about supporting `tf.train.MonitoredSession ` in Horovod? Because in TF api [recommends](https://www.tensorflow.org/api_docs/python/tf/train/SingularMonitoredSession) using this instead of other sessions such as `tf.train.SingularMonitoredSession`.

**Comment by alsrgv** [comment] 2017-11-07 21:56
[This example](https://github.com/uber/horovod/blob/master/examples/tensorflow_mnist.py) is using `MonitoredTrainingSession`. It should be supported.

**Comment by HamedMP** [comment] 2017-11-07 21:59
Nice, I will explore the compatibility of `tf.data` and different kinds of Sessions, can be on other TF distributed examples too, will let you know about the results.

**Comment by alsrgv** [comment] 2017-11-07 22:01
I will close this issue, since it was about `bool` datatype support, but feel free to open another one about `tf.data` & Sessions, or any other question!

**Closed by alsrgv** 2017-11-07 22:01 UTC
Labels: enhancement

**Comment by HamedMP** [comment] 2017-11-07 22:02
Yes, definitely, thank you for the support.
